import streamlit as st

dictionaries = { "1": ("huasa",{
    "hello": "sannu",
    "thank you": "na gode",
    "please": "don Allha",
    "yes": "iya",
    "no": "a'a",
    "water": "ruwa",
    "food": "abinci",
    "house": "gida",
    "friend": "aboki",
    "love": "soyayya",
    "mother": "uwa",
    "father": "uba",
    "child": "yaro",
    "school": "mkaranta",
    "book": "lattafi",
    "sun": "rana",
    "moon": "wata",
    "market": "kasuwa",
    "work": "aiki",
    "money": "kudi"}), "2":("igbo",{ "hello": "ndewo",
    "thank you": "daalụ",
    "please": "biko",
    "yes": "ee",
    "no": "mba",
    "water": "mmiri",
    "food": "nri",
    "house": "ụlọ",
    "friend": "enyi",
    "love": "ịhụnanya",
    "mother": "nne",
    "father": "nna",
    "child": "nwa",
    "school": "ụlọ akwụkwọ",
    "book": "akwụkwọ",
    "sun": "anyanwụ",
    "moon": "ọnwa",
    "market": "ahịa",
    "work": "ọrụ",
    "money": "ego"}), "3":("Yoruba",{
    "hello": "báwo",
    "thank you": "ẹ ṣé",
    "please": "jọ̀wọ́",
    "yes": "béẹ̀ni",
    "no": "rárá",
    "water": "omi",
    "food": "oúnjẹ",
    "house": "ilé",
    "friend": "ọ̀rẹ́",
    "love": "ìfẹ́",
    "mother": "ìyá",
    "father": "bàbá",
    "child": "ọmọ",
    "school": "ilé-ẹ̀kọ́",
    "book": "ìwé",
    "sun": "oorun",
    "moon": "oṣùpá",
    "market": "ọjà",
    "work": "iṣẹ́",
    "money": "owó",}),"4": ("Edo", {
    "hello": "ẹdọ",
    "thank you": "òsẹ",
    "please": "vbèè",
    "yes": "ẹ̀ẹ̀",
    "no": "ọ́vọ́",
    "water": "àmẹ̀",
    "food": "ẹmà",
    "house": "òwá",
    "friend": "èhòò",
    "love": "ífuán",
    "mother": "ìyẹ́",
    "father": "òbà",
    "child": "òmọ",
    "school": "èkó",
    "book": "ìvè",
    "sun": "òvèvè",
    "moon": "ùyẹ̀dẹ̀",
    "market": "èkèn",
    "work": "èmà",
    "money": "ígò",}),"5": ("Tiv", {
    "hello": "ngoohom",
    "thank you": "msugh",
    "please": "nenge",
    "yes": "ẽẽ",
    "no": "kpa",
    "water": "nyor",
    "food": "ikyoov",
    "house": "ate",
    "friend": "iortar",
    "love": "kwase",
    "mother": "mngu",
    "father": "ter",
    "child": "wan",
    "school": "ishima",
    "book": "ortar",
    "sun": "ior",
    "moon": "ter",
    "market": "kasua",
    "work": "isheev",
    "money": "mba",})
}
languages = {lang: words for _, (lang, words) in dictionaries.items()}

st.title("English → Nigerian Language Translator")

language = st.selectbox("Choose a language:", list(languages.keys()))
word = st.text_input("Enter an English word:")

if st.button("Translate"):
    if word in languages[language]:
        st.success(f"Translation: {languages[language][word]}")
    else:
        st.error("Word not found")
